#version 450
#extension GL_GOOGLE_include_directive : enable
#include "./common.glsl"

#define key_t uint

layout (std430, set = 0, binding = 0) readonly buffer SortedList {
    key_t keys[];
};

layout (std430, set = 0, binding = 1) writeonly buffer Out {
    uint boundaries[];
};

layout( push_constant ) uniform Constants
{
    uint numInstances;
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= numInstances) {
        return;
    }

    uint key = keys[index] >> 16;
    if (index == 0) {
        boundaries[key * 2] = index;
    } else {
        uint prevKey = (keys[index - 1] >> 16);
        if (key != prevKey) {
            boundaries[key * 2] = index;
            boundaries[prevKey * 2 + 1] = index;
        }
    }
    if (index == numInstances - 1) {
        boundaries[key * 2 + 1] = numInstances;
    }
}