#version 460
#extension GL_GOOGLE_include_directive: enable
#include "../common.glsl"

#define WORKGROUP_SIZE 256
#define RADIX_SORT_BINS 256

#define key_t TileDepth

layout (local_size_x = WORKGROUP_SIZE) in;

layout (push_constant, std430) uniform PushConstants {
    uint g_num_elements;
    uint g_shift;
    uint g_num_workgroups;
    uint g_num_blocks_per_workgroup;
};

layout (std430, set = 0, binding = 0) buffer elements_in {
    key_t g_elements_in[];
};

layout (std430, set = 0, binding = 1) buffer histograms {
    uint g_histograms[];
};

shared uint[RADIX_SORT_BINS] temp_histogram;

void main() {
    uint lID = gl_LocalInvocationID.x;
    uint wID = gl_WorkGroupID.x;

    if (lID < RADIX_SORT_BINS) {
        temp_histogram[lID] = 0;
    }
    barrier();

    for (uint index = 0; index < g_num_blocks_per_workgroup; index++) {
        uint elementId = wID * g_num_blocks_per_workgroup * WORKGROUP_SIZE + index * WORKGROUP_SIZE + lID;

        if (elementId < g_num_elements) {
            key_t key = g_elements_in[elementId];

            uint select_key = (g_shift < 32) ? key.low : key.high;
            uint binID = (select_key >> (g_shift & 31)) & uint(RADIX_SORT_BINS - 1);

            atomicAdd(temp_histogram[binID], 1u);
        }
    }
    barrier();

    if (lID < RADIX_SORT_BINS) {
        g_histograms[RADIX_SORT_BINS * wID + lID] = temp_histogram[lID];
    }
}